// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKwPT9XAXAfQ1YOrGTHLy236XNRHO4wHY',
    appId: '1:157890647464:web:1f32d133a65bfb4992399d',
    messagingSenderId: '157890647464',
    projectId: 'todoapp-11a58',
    authDomain: 'todoapp-11a58.firebaseapp.com',
    storageBucket: 'todoapp-11a58.firebasestorage.app',
    measurementId: 'G-XT4L6ELCFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1A69TZO0BpD5058Dkd-LgQH-tU21UelU',
    appId: '1:157890647464:android:de0b0cf16b213b6d92399d',
    messagingSenderId: '157890647464',
    projectId: 'todoapp-11a58',
    storageBucket: 'todoapp-11a58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfz7OFCit-yOtfWenvOcF4XMJhAo6F80',
    appId: '1:157890647464:ios:451876da1ca78f4492399d',
    messagingSenderId: '157890647464',
    projectId: 'todoapp-11a58',
    storageBucket: 'todoapp-11a58.firebasestorage.app',
    iosBundleId: 'com.todoapp.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfz7OFCit-yOtfWenvOcF4XMJhAo6F80',
    appId: '1:157890647464:ios:451876da1ca78f4492399d',
    messagingSenderId: '157890647464',
    projectId: 'todoapp-11a58',
    storageBucket: 'todoapp-11a58.firebasestorage.app',
    iosBundleId: 'com.todoapp.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKwPT9XAXAfQ1YOrGTHLy236XNRHO4wHY',
    appId: '1:157890647464:web:1a620c57f5386fb292399d',
    messagingSenderId: '157890647464',
    projectId: 'todoapp-11a58',
    authDomain: 'todoapp-11a58.firebaseapp.com',
    storageBucket: 'todoapp-11a58.firebasestorage.app',
    measurementId: 'G-D181GE49CK',
  );
}
